export const headerTexts = {
  us: {
    navigation: {
      news: 'News',
      social: 'Research',
      explore: 'Insights',
      technology: 'Voices',
      trending: 'Trending',
      learn: 'Tutorials',
      allCategories: 'All Categories',
      collections: 'Collections',
      myCollections: 'My Collections',
      categories: {
        news: 'News',
        insights: 'Insights',
        research: 'Research',
        voices: 'Voices',
      },
    },
    locale: {
      northAmerica: 'North America',
      asia: 'Asia',
      region: 'Region',
      switchToAsia: 'Switch to Asia',
    },
    actions: {
      search: 'Search',
      switchLanguage: 'Switch Language',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      expandNews: 'Expand news',
      collapseNews: 'Collapse news',
      expandResearch: 'Expand research',
      collapseResearch: 'Collapse research',
      expandInsights: 'Expand insights',
      collapseInsights: 'Collapse insights',
      expandVoices: 'Expand voices',
      collapseVoices: 'Collapse voices',
      expandCollections: 'Expand collections',
      collapseCollections: 'Collapse collections',
      expandTutorials: 'Expand tutorials',
      collapseTutorials: 'Collapse tutorials',
    },
    user: {
      dashboard: 'Dashboard',
    },
    messages: {
      pleaseLoginFirst: 'Please login first to access',
    },
    dropdown: {
      article: 'Article',
      newsGroups: [
        {
          key: 'technology',
          name: 'Technology',
          items: ['New Releases', 'Feature Updates', 'Models', 'Agents', 'Tools', 'Skills'],
        },
        {
          key: 'business',
          name: 'Business',
          items: ['Press Release', 'Funding', 'Reports', 'Enterprise Adoption'],
        },
        {
          key: 'hardware',
          name: 'Hardware',
          items: ['Chips', 'Military', 'Robotics', 'Drone', 'Energy'],
        },
        {
          key: 'policy',
          name: 'Policy',
          items: ['Regulation', 'Safety & Ethics', 'Geopolitics'],
        },
      ],
      researchItems: ['Benchmarks', 'Breakthroughs', 'Context', 'RAG', 'Labs'],
      insightsItems: ['Competition', 'Adoption', 'New Players', 'Trend Watch'],
      voicesItems: ['Talks', 'Blogs'],
      tutorialsItems: ['Glossary', 'Prompting', 'Playbooks', 'Workflows', 'Vibe Coding'],
    },
  },
  asia: {
    navigation: {
      news: '新闻',
      social: '研究',
      explore: '洞察',
      technology: '观点',
      trending: '热门',
      learn: '教程',
      allCategories: '全部分类',
      collections: '收藏',
      myCollections: '我的收藏',
      categories: {
        news: '新闻',
        insights: '洞察',
        research: '研究',
        voices: '观点',
      },
    },
    locale: {
      northAmerica: '北美',
      asia: '亚洲',
      region: '地区',
    },
    actions: {
      search: '搜索',
      switchLanguage: '切换语言',
      openMenu: '打开菜单',
      closeMenu: '关闭菜单',
      expandNews: '展开新闻',
      collapseNews: '收起新闻',
      expandResearch: '展开研究',
      collapseResearch: '收起研究',
      expandInsights: '展开洞察',
      collapseInsights: '收起洞察',
      expandVoices: '展开观点',
      collapseVoices: '收起观点',
      expandCollections: '展开收藏',
      collapseCollections: '收起收藏',
      expandTutorials: '展开教程',
      collapseTutorials: '收起教程',
    },
    user: {
      dashboard: '仪表板',
    },
    messages: {
      pleaseLoginFirst: '请先登录后再访问',
    },
    dropdown: {
      article: '文章',
      newsGroups: [
        {
          key: 'technology',
          name: '技术',
          items: ['新品发布', '功能更新', '模型', '智能体', '工具', '技能'],
        },
        {
          key: 'business',
          name: '商业',
          items: ['新闻稿', '融资', '报告', '企业采用'],
        },
        {
          key: 'hardware',
          name: '硬件',
          items: ['芯片', '军事', '机器人', '无人机', '能源'],
        },
        {
          key: 'policy',
          name: '政策',
          items: ['监管', '安全与伦理', '地缘政治'],
        },
      ],
      researchItems: ['基准测试', '突破', '上下文', 'RAG', '实验室'],
      insightsItems: ['竞争', '采用', '新玩家', '趋势观察'],
      voicesItems: ['访谈', '博客'],
      tutorialsItems: ['术语表', '提示工程', '操作手册', '工作流', '氛围编程'],
    },
  },
};
export const HEADER_LOGO_BLACK_URL = 'https://cdn.detake.com/icons/favicon-green.svg';

export type HeaderTexts = typeof headerTexts.us;
