export const headerTexts = {
  en: {
    navigation: {
      news: 'News',
      social: 'Research',
      explore: 'Insights',
      technology: 'Voices',
      trending: 'Trending',
      learn: 'Tutorials',
      allCategories: 'All Categories',
      collections: 'Collections',
      myCollections: 'My Collections',
      categories: {
        news: 'News',
        insights: 'Insights',
        research: 'Research',
        voices: 'Voices',
      },
    },
    locale: {
      northAmerica: 'North America',
      asia: 'Asia',
      region: 'Region',
      switchToAsia: 'Switch to Asia',
    },
    actions: {
      search: 'Search',
      popular: 'Popular',
      switchLanguage: 'Switch Language',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      expandNews: 'Expand news',
      collapseNews: 'Collapse news',
      expandResearch: 'Expand research',
      collapseResearch: 'Collapse research',
      expandInsights: 'Expand insights',
      collapseInsights: 'Collapse insights',
      expandVoices: 'Expand voices',
      collapseVoices: 'Collapse voices',
      expandCollections: 'Expand collections',
      collapseCollections: 'Collapse collections',
      expandTutorials: 'Expand tutorials',
      collapseTutorials: 'Collapse tutorials',
    },
    user: {
      dashboard: 'Dashboard',
    },
    messages: {
      pleaseLoginFirst: 'Please login first to access',
    },
    dropdown: {
      internationalEdition: 'International Edition',
      article: 'Article',
      newsGroups: [
        {
          key: 'technology',
          name: 'Technology',
          items: ['New Releases', 'Feature Updates', 'Models', 'Agents', 'Tools', 'Skills'],
        },
        {
          key: 'business',
          name: 'Business',
          items: ['Press Release', 'Funding', 'Reports', 'Enterprise Adoption'],
        },
        {
          key: 'hardware',
          name: 'Hardware',
          items: ['Chips', 'Military', 'Robotics', 'Drone', 'Energy'],
        },
        {
          key: 'policy',
          name: 'Policy',
          items: ['Regulation', 'Safety & Ethics', 'Geopolitics'],
        },
      ],
      researchItems: ['Benchmarks', 'Breakthroughs', 'Context', 'RAG', 'Labs'],
      insightsItems: ['Competition', 'Adoption', 'New Players', 'Trend Watch'],
      voicesItems: ['Talks', 'Blogs', 'Podcasts'],
      tutorialsItems: ['Glossary', 'Prompting', 'Playbooks', 'Workflows', 'Vibe Coding'],
    },
  },
  zh: {
    navigation: {
      news: '新闻',
      social: '研究',
      explore: '洞察',
      technology: '观点',
      trending: '热门',
      learn: '教程',
      allCategories: '全部分类',
      collections: '收藏',
      myCollections: '我的收藏',
      categories: {
        news: '新闻',
        insights: '洞察',
        research: '研究',
        voices: '观点',
      },
    },
    locale: {
      northAmerica: '北美',
      asia: '亚洲',
      region: '地区',
    },
    actions: {
      search: '搜索',
      popular: '热门推荐',
      switchLanguage: '切换语言',
      openMenu: '打开菜单',
      closeMenu: '关闭菜单',
      expandNews: '展开新闻',
      collapseNews: '收起新闻',
      expandResearch: '展开研究',
      collapseResearch: '收起研究',
      expandInsights: '展开洞察',
      collapseInsights: '收起洞察',
      expandVoices: '展开观点',
      collapseVoices: '收起观点',
      expandCollections: '展开收藏',
      collapseCollections: '收起收藏',
      expandTutorials: '展开教程',
      collapseTutorials: '收起教程',
    },
    user: {
      dashboard: '仪表板',
    },
    messages: {
      pleaseLoginFirst: '请先登录后再访问',
    },
    dropdown: {
      internationalEdition: '国际版',
      article: '文章',
      newsGroups: [
        {
          key: 'technology',
          name: '技术',
          items: ['新品发布', '功能更新', '模型', '智能体', '工具', '技能'],
        },
        {
          key: 'business',
          name: '商业',
          items: ['新闻稿', '融资', '报告', '企业采用'],
        },
        {
          key: 'hardware',
          name: '硬件',
          items: ['芯片', '军事', '机器人', '无人机', '能源'],
        },
        {
          key: 'policy',
          name: '政策',
          items: ['监管', '安全与伦理', '地缘政治'],
        },
      ],
      researchItems: ['基准测试', '突破', '上下文', 'RAG', '实验室'],
      insightsItems: ['竞争', '采用', '新玩家', '趋势观察'],
      voicesItems: ['访谈', '博客', '播客'],
      tutorialsItems: ['术语表', '提示工程', '操作手册', '工作流', '氛围编程'],
    },
  },
  ja: {
    navigation: {
      news: 'ニュース',
      social: 'リサーチ',
      explore: 'インサイト',
      technology: 'ボイス',
      trending: 'トレンド',
      learn: 'チュートリアル',
      allCategories: 'すべてのカテゴリ',
      collections: 'コレクション',
      myCollections: 'マイコレクション',
      categories: {
        news: 'ニュース',
        insights: 'インサイト',
        research: 'リサーチ',
        voices: 'ボイス',
      },
    },
    locale: {
      northAmerica: '北米',
      asia: 'アジア',
      region: '地域',
      switchToAsia: 'アジアに切り替え',
    },
    actions: {
      search: '検索',
      popular: '人気記事',
      switchLanguage: '言語を切り替え',
      openMenu: 'メニューを開く',
      closeMenu: 'メニューを閉じる',
      expandNews: 'ニュースを展開',
      collapseNews: 'ニュースを折りたたむ',
      expandResearch: 'リサーチを展開',
      collapseResearch: 'リサーチを折りたたむ',
      expandInsights: 'インサイトを展開',
      collapseInsights: 'インサイトを折りたたむ',
      expandVoices: 'ボイスを展開',
      collapseVoices: 'ボイスを折りたたむ',
      expandCollections: 'コレクションを展開',
      collapseCollections: 'コレクションを折りたたむ',
      expandTutorials: 'チュートリアルを展開',
      collapseTutorials: 'チュートリアルを折りたたむ',
    },
    user: {
      dashboard: 'ダッシュボード',
    },
    messages: {
      pleaseLoginFirst: 'アクセスするにはログインしてください',
    },
    dropdown: {
      internationalEdition: 'インターナショナル版',
      article: '記事',
      newsGroups: [
        {
          key: 'technology',
          name: 'テクノロジー',
          items: ['新規リリース', '機能更新', 'モデル', 'エージェント', 'ツール', 'スキル'],
        },
        {
          key: 'business',
          name: 'ビジネス',
          items: ['プレスリリース', '資金調達', 'レポート', '企業導入'],
        },
        {
          key: 'hardware',
          name: 'ハードウェア',
          items: ['チップ', '軍事', 'ロボティクス', 'ドローン', 'エネルギー'],
        },
        {
          key: 'policy',
          name: '政策',
          items: ['規制', '安全と倫理', '地政学'],
        },
      ],
      researchItems: ['ベンチマーク', 'ブレークスルー', 'コンテキスト', 'RAG', '研究所'],
      insightsItems: ['競争', '採用', '新規プレイヤー', 'トレンドウォッチ'],
      voicesItems: ['トーク', 'ブログ', 'ポッドキャスト'],
      tutorialsItems: ['用語集', 'プロンプト', 'プレイブック', 'ワークフロー', 'バイブコーディング'],
    },
  },
};
export const HEADER_LOGO_BLACK_URL = 'https://cdn.detake.com/icons/favicon-green.svg';

export type HeaderTexts = typeof headerTexts.en;
