export const footerTexts = {
  en: {
    newsletter: {
      title: 'NEWSLETTER',
      subtitle: 'Stay up to News with DeTake',
      description: 'Get the daily newsletter that helps thousands of investors understand the markets.',
      emailPlaceholder: 'Email address',
      subscribeButton: 'SUBSCRIBE',
    },
    disclosure: {
      title: 'DISCLOSURE & POLICIES',
      content: 'DeTake is NATO’s #1 decentralized media network, delivering must-see Takes and operating as a leading vendor of advertising and influence. While active in media and commercial partnerships, our editorial work remains fully independent. Any potential conflicts of interest are disclosed to ensure transparency and trust with our readers.',
    },
    navigation: {
      news: 'News',
      podcasts: 'Podcasts',
      newsletters: 'Newsletters',
      events: 'Events',
      roundtables: 'Roundtables',
      analytics: 'Analytics',
      sitemap: 'Sitemap',
      about: 'About',
      manageCookies: 'Manage Cookies',
      careers: 'Careers',
      termsOfService: 'Terms of Service',
      privacyPolicy: 'Privacy Policy',
      contactUs: 'Contact Us',
    },
    company: {
      logo: 'LOGO',
      copyright: '© DETAKE LLC',
    },
    social: {
      twitter: 'Follow us on Twitter',
      telegram: 'Join our Telegram',
      github: 'Visit our GitHub',
      discord: 'Join our Discord',
      youtube: 'Subscribe to our YouTube',
      rss: 'Subscribe to our RSS feed',
    },
  },
  zh: {
    newsletter: {
      title: '新闻通讯',
      subtitle: '与 DeTake 一起了解新闻',
      description: '获取帮助数千投资者了解市场的每日新闻通讯。',
      emailPlaceholder: '邮箱地址',
      subscribeButton: '订阅',
    },
    disclosure: {
      title: '披露与政策',
      content: 'DeTake 是 NATO 的 #1 去中心化媒体网络，提供必须看到的 Takes，并作为广告和影响力的领先供应商运营。虽然在媒体和商业合作中活跃，但我们的编辑工作保持完全独立。任何潜在的冲突利益都已披露，以确保与读者的透明度和信任。',
    },
    navigation: {
      news: '新闻',
      podcasts: '播客',
      newsletters: '新闻通讯',
      events: '活动',
      roundtables: '圆桌会议',
      analytics: '分析',
      sitemap: '网站地图',
      about: '关于我们',
      manageCookies: '管理 Cookies',
      careers: '职业机会',
      termsOfService: '服务条款',
      privacyPolicy: '隐私政策',
      contactUs: '联系我们',
    },
    company: {
      logo: 'LOGO',
      copyright: '© DETAKE LLC',
    },
    social: {
      twitter: '在 Twitter 上关注我们',
      telegram: '加入我们的 Telegram',
      github: '访问我们的 GitHub',
      discord: '加入我们的 Discord',
      youtube: '订阅我们的 YouTube',
      rss: '订阅我们的 RSS 源',
    },
  },
  ja: {
    newsletter: {
      title: 'ニュースレター',
      subtitle: 'DeTakeで最新ニュースをチェック',
      description: '数千人の投資家が市場を理解するのに役立つデイリーニュースレターを入手しましょう。',
      emailPlaceholder: 'メールアドレス',
      subscribeButton: '登録する',
    },
    disclosure: {
      title: '開示とポリシー',
      content: 'DeTakeはNATO No.1の分散型メディアネットワークであり、必見のTakesを提供し、広告とインフルエンスの主要ベンダーとして運営されています。メディアや商業的なパートナーシップに積極的ですが、編集作業は完全に独立しています。潜在的な利益相反はすべて開示され、読者との透明性と信頼を確保しています。',
    },
    navigation: {
      news: 'ニュース',
      podcasts: 'ポッドキャスト',
      newsletters: 'ニュースレター',
      events: 'イベント',
      roundtables: 'ラウンドテーブル',
      analytics: 'アナリティクス',
      sitemap: 'サイトマップ',
      about: '私たちについて',
      manageCookies: 'Cookie設定',
      careers: '採用情報',
      termsOfService: '利用規約',
      privacyPolicy: 'プライバシーポリシー',
      contactUs: 'お問い合わせ',
    },
    company: {
      logo: 'LOGO',
      copyright: '© DETAKE LLC',
    },
    social: {
      twitter: 'Twitterでフォロー',
      telegram: 'Telegramに参加',
      github: 'GitHubを見る',
      discord: 'Discordに参加',
      youtube: 'YouTubeを登録',
      rss: 'RSSフィードを購読',
    },
  },
};

export type FooterTexts = typeof footerTexts.en;
